export { fetchProfiles, saveProfile, type FleetProfile, type FleetProfileInput } from './profiles.api';
export {
  fetchMachine,
  requestUpdate,
  installAgent,
  rescanMachine,
  fetchRecentJobs,
  type RecentJob,
  type Severity,
  type VulnPackage,
  type VulnSummary,
  type MachineVulns,
  type MachineDetail,
  type MachineInventory,
  type AgentJob,
} from './machines.api';
export {
  fetchProducts,
  createProduct,
  updateProduct,
  deleteProduct,
  setMachineProduct,
  fetchPlan,
  addSlots,
  applyTemplate,
  deleteSlot,
  issueSlotKey,
  assignToSlot,
  fetchTemplates,
  createTemplate,
  deleteTemplate,
  type Product,
  type PlanSlot,
  type SlotKind,
  type TemplateItem,
  type FleetTemplate,
} from './plan.api';
